#ifndef H_TYPEDEFS
#define H_TYPEDEFS

enum BLOCK_SIZE {SIZE_SMALL = 0, SIZE_LARGE = 1};
enum ORIENTATION {ORIENT_FORWARD = 0, ORIENT_BACKWARD, ORIENT_UP, ORIENT_DOWN, ORIENT_LEFT, ORIENT_RIGHT};

#endif // H_TYPEDEFS

